FROM node:14-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV PRISMA_CLI_BINARY_TARGETS=linux-musl

COPY . .

WORKDIR /app/packages/backend
RUN yarn install --production
RUN yarn build

CMD yarn start:prod
